quarkus:
  http:
    port: 8080
  smallrye-jwt:
    auth-mechanism: MP-JWT
    realm-name: e-learning
    enabled: true
    token:
      header: Authorization
      cookie: none
      bearer-only: true
    verify:
      public-key-location: publicKey.pem
      issuer: https://elearning.local

mp:
  jwt:
    verify:
      issuer: https://elearning.local

quarkus:
  mongodb:
    connection-string: mongodb://localhost:27017
    database: elearning
